from typing import Optional, List
from abc import ABC, abstractmethod
from vdx_py.mpcc import MPCC

import casadi as ca
import numpy as np

from ..nosnoc_types import RKRepresentation
from ..rk import IntegralRKRepresentation, DifferentialRKRepresentation, LiftedDifferentialRKRepresentation

class Base(ABC,MPCC):
    r"""
    Base class for MPCCs generated by nosnoc.
    """
    def __init__(self, dcs, opts):
        super().__init__()
        self.dcs = dcs
        self.model = dcs.model
        self.opts = opts
        if self.opts.rk_representation == RKRepresentation.INTEGRAL:
            self.rk = IntegralRKRepresentation(self.opts.n_s, self.opts.rk_scheme)
        elif self.opts.rk_representation == RKRepresentation.DIFFERENTIAL:
            self.rk = DifferentialRKRepresentation(self.opts.n_s, self.opts.rk_scheme)
        elif self.opts.rk_representation == RKRepresentation.DIFFERENTIAL_LIFT_X:
            self.rk = LiftedDifferentialRKRepresentation(self.opts.n_s, self.opts.rk_scheme)

    def populate_problem(self):
        self._create_variables()
        self._create_parameters()
        self._generate_direct_transcription_constraints()
        self._generate_complementarity_constraints()
        self._generate_step_equilibration_constraints()

    @abstractmethod
    def _create_variables(self):
        """Create Optimization Variables"""
        pass

    @abstractmethod
    def _generate_direct_transcription_constraints(self):
        """Create direct transcription constraints"""
        pass

    @abstractmethod
    def _generate_complementarity_constraints(self):
        """Create complementarity constraints"""
        pass

    @abstractmethod
    def _generate_step_equilibration_constraints(self):
        """Create step equilibration constraints"""
        pass
