from typing import Optional, List
from abc import ABC, abstractmethod

import casadi as ca
import numpy as np
from ..mpcc import MPCC
from vdx.vartypes import *

from ..nosnoc_types import RKRepresentation, ConstraintRelaxationMode
from ..rk import IntegralRKRepresentation, DifferentialRKRepresentation, LiftedDifferentialRKRepresentation

class Base(ABC,MPCC):
    r"""
    Base class for MPCCs generated by nosnoc.
    """
    def __init__(self, dcs, opts):
        super().__init__()
        self.dcs = dcs
        self.model = dcs.model
        self.opts = opts
        if self.opts.rk_representation == RKRepresentation.INTEGRAL:
            self.rk = IntegralRKRepresentation(self.opts.n_s, self.opts.rk_scheme)
        elif self.opts.rk_representation == RKRepresentation.DIFFERENTIAL:
            self.rk = DifferentialRKRepresentation(self.opts.n_s, self.opts.rk_scheme)
        elif self.opts.rk_representation == RKRepresentation.DIFFERENTIAL_LIFT_X:
            self.rk = LiftedDifferentialRKRepresentation(self.opts.n_s, self.opts.rk_scheme)

        self.rbp = 1 if not self.rk.is_right_boundary_explicit() else 0

    def populate_problem(self):
        self._create_variables()
        self._create_parameters()
        self._generate_direct_transcription_constraints()
        self._generate_complementarity_constraints()
        self._generate_step_equilibration_constraints()

    def _create_parameters(self):
        self.p.rho_h[()] = Parameter("rho_h", 1, val=self.opts.rho_h)
        self.p.rho_terminal[()] = Parameter("rho_terminal", 1, val=self.opts.rho_terminal)
        self.p.T[()] = Parameter("T", 1, val=self.opts.T)
        self.p.p_global[()] = Parameter("p_global", self.dcs.dims.n_p_global, val=self.model.p_global_val)
        self.p.p_time_var[range(1,self.opts.N_stages+1)] = Parameter(f"p_time_var", self.dcs.dims.n_p_time_var, val=self.model.p_time_var_val)

    def _create_global_variables(self):
        opts = self.opts
        dcs = self.dcs
        model = self.model
        dims = self.dcs.dims

        self.w.v_global[()] = Primal("v_global",
                                     dims.n_v_global,
                                     init=model.v0_global,
                                     lb=model.lbv_global,
                                     ub=model.ubv_global)
        if opts.time_optimal_problem:
            self.w.T_final[()] = Primal("T_final", 1, lb=opts.T_final_min, ub=opts.T_final_max, init=opts.T)
            self.f += self.w.T_final[()]

    def _create_speed_of_time_variables(self):
        opts = self.opts
        if opts.use_speed_of_time_variables:
            if opts.local_speed_of_time_variable:
                self.w.sot[range(1,opts.N_stages+1)] = Primal("sot",
                                                             1,
                                                             init=opts.s_sot0,
                                                             lb=opts.s_sot_min,
                                                             ub=opts.s_sot_max)
            else:
                self.w.sot[()] = Primal("sot",
                                        1,
                                        init=opts.s_sot0,
                                        lb=opts.s_sot_min,
                                        ub=opts.s_sot_max)


    def _create_initial_variables(self):
        opts = self.opts
        dcs = self.dcs
        model = self.model
        dims = self.dcs.dims
        self.w.x[(0,0,opts.n_s)] = Primal(f"x_0", dims.n_x,
                                          lb=model.x0,
                                          ub=model.x0,
                                          init=model.x0)
        self.w.z[(0,0,opts.n_s)] = Primal(f"z_0", dims.n_z,
                                          lb=model.lbz,
                                          ub=model.ubz,
                                          init=model.z0)

    def _create_h(self, ii):
        opts = self.opts
        dcs = self.dcs
        model = self.model
        dims = self.dcs.dims
        h0 = opts.h_k[ii-1]/opts.N_finite_elements[ii-1]
        if opts.use_fesd:
            ubh = (1 + opts.gamma_h) * h0 # upper bound for FE length
            lbh = (1 - opts.gamma_h) * h0 # lower bound for FE length
            if opts.time_rescaling() and not opts.use_speed_of_time_variables:
                # if only time_rescaling is true, speed of time and step size all lumped together, e.g., \hat{h}_{k,i} = s_n * h_{k,i}, hence the bounds need to be extended.
                ubh = ubh*opts.s_sot_max
                lbh = lbh/opts.s_sot_min
            elif opts.time_optimal_problem:
                ubh = ubh*(opts.T_final_max/opts.T)
                lbh = lbh/((opts.T_final_min+1e-8)/opts.T)

            self.w.h[ii,range(1,opts.N_finite_elements[ii-1]+1)] = Primal(f"h", 1,
                                                                          lb=lbh,
                                                                          ub=ubh,
                                                                          init=h0)

    def _create_u(self):
        self.w.u[range(1,self.opts.N_stages+1)] = Primal(f"u", self.dcs.dims.n_u,
                                                    lb=self.model.lbu,
                                                    ub=self.model.ubu,
                                                    init=self.model.u0)

    def _handle_x_box_constraints(self):
        opts = self.opts
        dcs = self.dcs
        model = self.model
        dims = self.dcs.dims
        rbp = self.rbp
        # Handle x_box settings (i.e., manage at which points the box constraints are enforced)
        for ii in range(1,opts.N_stages+1):
            if not opts.x_box_at_stg and not opts.rk_representation == RKRepresentation.DIFFERENTIAL:
                self.w.x[ii,range(1,opts.N_finite_elements[ii-1]+1),range(1, opts.n_s-rbp)](lb=-np.inf, ub=np.inf)

            if not opts.x_box_at_fe:
                self.w.x[ii,range(1, opts.N_finite_elements[ii-1]),opts.n_s+rbp](lb=-np.inf, ub=np.inf)

    def _create_xvz(self, ii):
        opts = self.opts
        dcs = self.dcs
        model = self.model
        dims = self.dcs.dims
        rbp = self.rbp
        if opts.rk_representation in (RKRepresentation.INTEGRAL,RKRepresentation.DIFFERENTIAL_LIFT_X):
            self.w.x[ii,range(1,opts.N_finite_elements[ii-1]+1),range(1,opts.n_s+rbp+1)] = Primal(f"x", dims.n_x,
                                                                                                  lb=model.lbx,
                                                                                                  ub=model.ubx,
                                                                                                  init=model.x0)
        else:
            self.w.x[ii,range(1,opts.N_finite_elements[ii-1]+1),opts.n_s+rbp] = Primal(f"x", dims.n_x,
                                                                                       lb=model.lbx,
                                                                                       ub=model.ubx,
                                                                                       init=model.x0)

        if opts.rk_representation in(RKRepresentation.DIFFERENTIAL,RKRepresentation.DIFFERENTIAL_LIFT_X):
            self.w.v[ii,range(1,opts.N_finite_elements[ii-1]+1),range(1,opts.n_s+1)] = Primal(f"v", dims.n_x)

        self.w.z[ii,range(1,opts.N_finite_elements[ii-1]+1),range(1,opts.n_s+rbp+1)] = Primal(f"z", dims.n_z,
                                                                                              lb=model.lbz,
                                                                                              ub=model.ubz,
                                                                                              init=model.z0)

    def _get_stage_parameters(self, ii):
        p_global = self.p.p_global[()].sym
        p_time_var = self.p.p_time_var[ii].sym
        return ca.vertcat(p_global, p_time_var)

    def _get_stage_sot(self, ii): # TODO(@anton) maybe this should be public
        if self.opts.use_speed_of_time_variables and self.opts.local_speed_of_time_variable:
            s_sot = self.w.sot[ii] # here, sot is a vector
        elif self.opts.use_speed_of_time_variables:
            s_sot = self.w.sot[()] # here, sot is a scalar
        else:
            s_sot = 1
        return s_sot

    def _get_stage_t(self,ii):
        if self.opts.time_optimal_problem and not self.opts.use_speed_of_time_variables:
            t_stage = self.w.T_final[()]/(self.opts.N_stages*self.opts.N_finite_elements[ii-1])
        elif self.opts.time_optimal_problem:
            t_stage = s_sot*self.p.T[()]/self.opts.N_stages
        else:
            t_stage = self.p.T[()]/self.opts.N_stages
        return t_stage

    def _get_fe_h(self, ii, jj):
        if self.opts.use_fesd:
            h = self.w.h[ii,jj]
        elif self.opts.time_optimal_problem and not self.opts.use_speed_of_time_variables:
            h = self.w.T_final[()]/(self.opts.N_stages*self.opts.N_finite_elements[ii-1])
        else:
            h = self.p.T[()].val/(self.opts.N_stages*self.opts.N_finite_elements[ii-1])
        return h

    def _get_x_end(self, ii, jj):
        return self.w.x[ii,jj,self.opts.n_s+self.rbp].sym

    def _build_prk(self, ii, jj):
        return ca.vertcat(
            self.w.u[ii],
            self.w.v_global[()],
            self._get_stage_parameters(ii)
        )

    def _build_z(self, ii, jj):
        z = []
        for kk in range(1,self.opts.n_s+1):
            z.append(self._get_rk_stage_z(ii,jj,kk))
        return z

    def _rk_stage_path_constraints(self, ii, jj, kk):
        if not self.opts.g_path_at_stg:
            return
        x = self.w.x[ii,jj,kk]
        z = self.w.z[ii,jj,kk]
        u = self.w.u[ii]
        v_global = self.w.v_global[()]
        p = self._get_stage_parameters(ii)
        self.g.path[ii,jj,kk] = Constraint(
            self.dcs.g_path_fun(x,z,u,v_global,p),
            lb=self.model.lbg_path,
            ub=self.model.ubg_path,
        )
        self.G.path[ii,jj,kk] = CConstraint(self.dcs.G_path_fun(x,z,u,v_global,p))
        self.H.path[ii,jj,kk] = CConstraint(self.dcs.H_path_fun(x,z,u,v_global,p))

    def _fe_path_constraints(self, ii, jj):
        if self.opts.g_path_at_stg or not self.opts.g_path_at_fe:
            return
        x = self.w.x[ii,jj,self.opts.n_s+self.rbp]
        z = self.w.z[ii,jj,self.opts.n_s+self.rbp]
        u = self.w.u[ii]
        v_global = self.w.v_global[()]
        p = self._get_stage_parameters(ii)
        self.g.path[ii,jj] = Constraint(
            self.dcs.g_path_fun(x,z,u,v_global,p),
            lb=self.model.lbg_path,
            ub=self.model.ubg_path,
        )
        self.G.path[ii,jj] = CConstraint(self.dcs.G_path_fun(x,z,u,v_global,p))
        self.H.path[ii,jj] = CConstraint(self.dcs.H_path_fun(x,z,u,v_global,p))

    def _stage_path_constraints(self, ii):
        if self.opts.g_path_at_stg or self.opts.g_path_at_fe:
            return
        x = self.w.x[ii,self.opts.N_finite_elements[ii-1],self.opts.n_s+self.rbp]
        z = self.w.z[ii,self.opts.N_finite_elements[ii-1],self.opts.n_s+self.rbp]
        u = self.w.u[ii]
        v_global = self.w.v_global[()]
        p = self._get_stage_parameters(ii)
        self.g.path[ii] = Constraint(
            self.dcs.g_path_fun(x,z,u,v_global,p),
            lb=self.model.lbg_path,
            ub=self.model.ubg_path,
        )
        self.G.path[ii] = CConstraint(self.dcs.G_path_fun(x,z,u,v_global,p))
        self.H.path[ii] = CConstraint(self.dcs.H_path_fun(x,z,u,v_global,p))

    def _terminal_constraint(self):
        # TODO(@anton) relaxation
        x = self.w.x[self.opts.N_stages,self.opts.N_finite_elements[self.opts.N_stages-1],self.opts.n_s+self.rbp]
        z = self.w.z[self.opts.N_stages,self.opts.N_finite_elements[self.opts.N_stages-1],self.opts.n_s+self.rbp]
        v_global = self.w.v_global[()]
        p_global = self.p.p_global[()]
        self.g.terminal[self.opts.N_stages+1] = Constraint(
            self.dcs.g_terminal_fun(x,z,v_global,p_global),
            lb=self.model.lbg_terminal,
            ub=self.model.ubg_terminal,
            relax=self._get_relaxation(self.opts.relax_terminal_constraint),
        )

    def _terminal_objective(self):
        x = self.w.x[self.opts.N_stages,self.opts.N_finite_elements[self.opts.N_stages-1],self.opts.n_s+self.rbp]
        z = self.w.z[self.opts.N_stages,self.opts.N_finite_elements[self.opts.N_stages-1],self.opts.n_s+self.rbp]
        v_global = self.w.v_global[()]
        p_global = self.p.p_global[()]
        self.f += self.dcs.f_q_T_fun(x,z,v_global,p_global)

    def _numerical_time_constraints(self,ii):
        opts = self.opts
        if opts.use_fesd and opts.equidistant_control_grid:
            # Create a vdx relaxation struct which holds the information needed by vdx to automatically
            # relax a constraint vector. It takes the type of relaxation, the name of the vdx.Variable
            # to store the slacks, and the name of the vdx.Variable to store the relaxation parameter.
            # This struct can be passed as the last element of the rhs of a vdx variable assignment.
            # See vdx documentation on relaxation: TODO add when vdx docs updated.
            # TODO(@anton) implement
            #relax_num_time_struct = vdx.RelaxationStruct(opts.relax_terminal_numerical_time.to_vdx, 's_numerical_time', 'rho_numerical_time')
            if opts.time_optimal_problem and not opts.time_freezing:
                # if time optimal and not time freezing we want T_final to be the rhs of the
                # equidistant control grid constraints.
                ecg_rhs = self.w.T_final[()]/opts.N_stages
            else:
                # if time freezing or not time optimal we want T to be the rhs of the
                # equidistant control grid constraints.
                ecg_rhs = self.p.T[()]/opts.N_stages

            sum_h = ca.sum2(self.w.h[ii,:])
            s_sot = self._get_stage_sot(ii)
            if opts.use_numerical_clock_state:
                curr_t = self.w.numerical_time[ii,opts.N_finite_elements[ii]]
                self.g.equidistant_numerical_grid[ii] = Constraint(curr_t - ii*ecg_rhs)
            else:
                if not opts.time_freezing:
                    self.g.equidistant_numerical_grid[ii] = Constraint(s_sot*sum_h - ecg_rhs)
                else:
                    self.g.equidistant_numerical_grid[ii] = Constraint(sum_h - ecg_rhs)

                    
                # vdx.RelaxationStruct.is_relaxed returns true if the relaxation is not `NONE`.
                # if relax_num_time_struct.is_relaxed:
                #     obj.p.rho_numerical_time().val = opts.rho_terminal_numerical_time

    def _terminal_numerical_time_constraints(self):
        opts = self.opts
        rbp = self.rbp

        if opts.time_freezing:
            raise NotImplementedError("time_freezing is not yet implemented")
            x0 = obj.w.x(0,0,opts.n_s)
            t0 = x0[-1]
            x_end = self.w.x[opts.N_stages,opts.N_finite_elements[opts.N_stages-1],opts.n_s+rbp]

            # Terminal Phyisical Time (Possible terminal constraint on the clock state if time freezing is active).
            if opts.time_optimal_problem:
                # in the case of time optimal time freezing problem, physical clock state must reach final time.
                self.g.terminal_physical_time[opts.N_stages+1] = Constraint(x_end[-1]-(self.w.T_final[()]+t0))

            elif opts.impose_terminal_phyisical_time and not opts.stagewise_clock_constraint:
                # in the case of a generic time freezing problem, physical clock state must reach final time if
                # we are imposing terminal physical time and we did not do so by apply stagewise constraints.
                self.g.terminal_physical_time[opts.N_stages+1] = Constraint(x_end[-1]-(self.p.T[()]+t0))

        elif not opts.use_fesd and opts.time_optimal_problem and opts.use_speed_of_time_variables:
            # without FESD we need speed of time variables and the sum of
            # h*sot must be equal to the final time.
            integral_clock_state = 0
            for ii in range(1,opts.N_stages+1):
                s_sot = self._get_stage_sot(ii)
                for jj in range(1,opts.N_finite_elements[ii-1]+1):
                    h = self.p.T[()]/(opts.N_stages*opts.N_finite_elements[ii-1])
                    integral_clock_state += h*s_sot
            self.g.integral_clock_state[opts.N_stages+1] = Constraint(integral_clock_state-self.w.T_final[()])

        elif not opts.equidistant_control_grid:
            # T_num = T_phy = T_final =  T.
            # all step sizes add up to prescribed time T.
            # if use_speed_of_time_variables = true, numerical time is decupled from the sot scaling (no mather if local or not):
            sum_h_all = ca.sum2(self.w.h[:,:])
            if not opts.time_optimal_problem:
                # not a time optimal problem so just sum of hs must be the terminal numerical time T.
                self.g.sum_h[opts.N_stages+1] = Constraint(sum_h_all-self.p.T[()])

            elif not opts.use_speed_of_time_variables:
                # a time optimal problem without sot so sum of hs must be the optimal terminal numerical time T_final.
                self.g.sum_h[opts.N_stages+1] = Constraint(sum_h_all-self.w.T_final[()])

            else:
                # a time optimal problem with sot so sum of h*sot must be the optimal terminal "physical" time T_final.
                # and the sum of h needs to be the terminal numerical time T
                integral_clock_state = 0
                for ii in range(1,opts.N_stages+1):
                    s_sot = self._get_stage_sot(ii)
                    for jj in range(1,opts.N_finite_elements[ii-1]+1):
                        h = self.w.h[ii,jj]
                        integral_clock_state = integral_clock_state + h*s_sot
                self.g.sum_h[opts.N_stages+1] = Constraint(sum_h_all-self.p.T[()])
                self.g.integral_clock[opts.N_stages+1] = Constraint(integral_clock_state-self.w.T_final[()])


    def _get_relaxation(self, relax_type: ConstraintRelaxationMode):
        if relax_type == ConstraintRelaxationMode.NONE:
            return HardConstraint()
        elif relax_type == ConstraintRelaxationMode.ELL_1:
            return Ell1Relaxation(self)
        elif relax_type == ConstraintRelaxationMode.ELL_2:
            return Ell2Relaxation(self)
        elif relax_type == ConstraintRelaxationMode.ELL_INF:
            return EllInfRelaxation(self)


    @abstractmethod
    def _get_rk_stage_z(self, ii, jj, kk):
        """Get the 'z' variables for a given rk stage"""
        pass

    @abstractmethod
    def _create_variables(self):
        """Create Optimization Variables"""
        pass

    @abstractmethod
    def _generate_direct_transcription_constraints(self):
        """Create direct transcription constraints"""
        pass

    @abstractmethod
    def _generate_complementarity_constraints(self):
        """Create complementarity constraints"""
        pass

    @abstractmethod
    def _generate_step_equilibration_constraints(self):
        """Create step equilibration constraints"""
        pass

    def _heuristic_mean(self):
        opts = self.opts
        for ii in range(1, opts.N_stages+1):
            for jj in range(1, opts.N_finite_elements[ii-1]+1):
                h0 = opts.h_k[ii-1]/opts.N_finite_elements[ii-1]
                self.f += self.p.rho_h[()]*(h0-self.w.h[ii,jj])**2

    def _heuristic_diff(self):
        opts = self.opts
        for ii in range(1, opts.N_stages+1):
            for jj in range(2, opts.N_finite_elements[ii-1]+1):
                self.f += self.p.rho_h[()]*(self.w.h[ii,jj]-self.w.h[ii,jj-1])**2
