name: report
on:
  workflow_run:
    workflows: [ "nosnoc tests" ]
    types: [ completed ]

permissions:
  checks: write
  pull_requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: 'test-results/results.xml'
          comment: true
          pr_id: ${{ github.event.workflow_run.pull_requests[0].number }}
